TRUE, FALSE = 'TRUE', 'FALSE'
STRING = 'STRING'
CHAR_CONST = 'CHAR_CONST'
INTEGER_CONST, FLOAT_CONST = 'INTEGER_CONST', 'FLOAT_CONST'
ID = 'ID'

INT, FLOAT, CHAR, VOID = 'INT', 'FLOAT', 'CHAR', 'VOID'

# operations
ADD_OP, SUB_OP, MUL_OP, DIV_OP, POWER_OP, MOD_OP = 'ADD_OP', 'SUB_OP', 'MUL_OP', 'DIV_OP', 'POWER_OP', 'MOD_OP'
AND_OP, OR_OP, NOT_OP = 'AND_OP', 'OR_OP', 'NOT_OP'
# negative operation, e.g -10
NEG_OP = 'NEG_OP'

LT_OP, GT_OP = 'LT', 'GT'
LE_OP, GE_OP = 'LE_OP', 'GE_OP'
EQ_OP, NE_OP = 'EQ_OP', 'NE_OP'

ASSIGN = 'ASSIGN'

LPAREN, RPAREN = 'LPAREN', 'RPAREN'
LBRACKET, RBRACKET = 'LBRACKET', 'RBRACKET'

COMMA, DOT, SEMICOLON, HASH = 'COMMA', 'DOT', 'SEMICOLON', 'HASH'
COLON, AMPERSAND_MARK = 'COLON', 'AMPERSAND_MARK'

IF, ELSE, FOR, WHILE, RETURN, DO = 'IF', 'ELSE', 'FOR', 'WHILE', 'RETURN', 'DO'
BREAK, CONTINUE = 'BREAK', 'CONTINUE'

BEGIN, END = 'BEGIN', 'END'
DEF_FUC = 'DEF_FUNC'
RETURN_FUNC = 'RETURN_FUNC'

EOF = 'EOF'

